### ISSUE TITLE
"TypeError: string indices must be integers" when working with primary sources

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-core#21]
```
$ /opt/encyc-core/venv/encyccore/bin/encyc articles --dryrun
Debug mode is off
2019-11-15 09:26:20.922909 hosts: [{'host': '192.168.0.20', 'port': '9200'}]
2019-11-15 09:26:20.923253 index: encyc-20180226c
2019-11-15 09:26:20.923323 ------------------------------------------------------------------------
2019-11-15 09:26:20.923347 getting mw_authors,articles...
2019-11-15 09:26:20.979365 getting es_articles...
2019-11-15 09:26:23.066878 mediawiki articles: 1604
2019-11-15 09:26:23.066943 elasticsearch articles: 1481
2019-11-15 09:26:23.066958 determining new,delete...
2019-11-15 09:26:23.284648 articles to update: 33
2019-11-15 09:26:23.284697 getting encycrg titles...
2019-11-15 09:26:30.702456 encycrg titles: 656
2019-11-15 09:26:30.702512 adding articles...
2019-11-15 09:26:30.702524 --------------------
2019-11-15 09:26:30.702533 1/33 The War Outside (book)
2019-11-15 09:26:30.702543 getting from mediawiki
Traceback (most recent call last):
  File "/opt/encyc-core/venv/encyccore/bin/encyc", line 14, in <module>
    load_entry_point('encyc-core===-', 'console_scripts', 'encyc')()
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/encyc/cli.py", line 180, in articles
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 32, in with_profiling
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 359, in articles
  File "build/bdist.linux-x86_64/egg/encyc/models/legacy.py", line 277, in page
  File "build/bdist.linux-x86_64/egg/encyc/models/legacy.py", line 365, in _mkpage
  File "build/bdist.linux-x86_64/egg/encyc/models/wikipage.py", line 50, in parse_mediawiki_text
  File "build/bdist.linux-x86_64/egg/encyc/models/wikipage.py", line 298, in _remove_primary_sources
TypeError: string indices must be integers
```

**Comment by gjost** [comment]
Not seeing this problem any more.
```
(encyccore) encyc@denshodeb9b:/opt/encyc-core$ encyc articles --title="The War Outside (book)"
2020-03-03 13:50:51.117101 ------------------------------------------------------------------------
2020-03-03 13:50:51.117215 getting mw_authors,articles...
2020-03-03 13:50:57.857687 getting es_articles...
2020-03-03 13:50:58.471127 mediawiki articles: 1604
2020-03-03 13:50:58.471219 elasticsearch articles: 1246
2020-03-03 13:50:58.471232 getting encycrg titles...
2020-03-03 13:50:59.037594 encycrg titles: 0
2020-03-03 13:50:59.037721 NO ENCYC-RG ARTICLES!!!
2020-03-03 13:50:59.037763 RUN "encyc articles --force" AFTER THIS PASS TO MARK rg/notrg LINKS
2020-03-03 13:50:59.037789 adding articles...
2020-03-03 13:50:59.037819 --------------------
2020-03-03 13:50:59.037852 1/1 The War Outside (book)
2020-03-03 13:50:59.038587 getting from mediawiki
2020-03-03 13:51:02.383725 exists in elasticsearch
2020-03-03 13:51:02.383831 creating page
2020-03-03 13:51:02.384583 saving articles "The War Outside (book)"
2020-03-03 13:51:03.400436 ok
2020-03-03 13:51:03.400504 NO ENCYC-RG ARTICLES!!!
2020-03-03 13:51:03.400530 RUN "encyc articles --force" AFTER THIS PASS TO MARK rg/notrg LINKS
2020-03-03 13:51:03.400544 NOTE: ENCYC-RG MUST BE ACCESSIBLE IN ORDER TO BUILD RG ARTICLES LIST.
2020-03-03 13:51:03.400575 DONE
2020-03-03 13:51:03.401093 TIME: 0:00:12.283978
(encyccore) encyc@denshodeb9b:/opt/encyc-core$
```

**Comment by gjost** [comment]
@GeoffFroh 2020-05-10:  Both encyc-core and encyc-rg installed without issues, and I have them pointed at the in-house ES7 as the backend since I'll need to make changes to the data. I was able to set up the index with the `encyc create` command, and was also able to populate the authors with `encyc authors`; but both `encyc articles` and `encyc sources` return the same error message which looks like it's related to sources in some way. 

Here's the sources terminal output:
```
$ encyc sources
2020-05-09 10:03:45.024303 ------------------------------------------------------------------------
2020-05-09 10:03:45.024489 getting sources from PSMS...
Traceback (most recent call last):
  File "/opt/encyc-core/venv/encyccore/bin/encyc", line 11, in <module>
    load_entry_point('encyc-core===-', 'console_scripts', 'encyc')()
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/cli.py", line 184, in sources
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/publish.py", line 28, in with_profiling
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/publish.py", line 304, in sources
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/models/legacy.py", line 407, in sources_all
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/models/legacy.py", line 407, in <listcomp>
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/models/legacy.py", line 134, in source
TypeError: string indices must be integers
```
The TypeError is the same message returned with the articles command; here's the bottom of the trace:
```
File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/models/wikipage.py", line 297, in _remove_primary_sources
  File "/opt/encyc-core/venv/encyccore/lib/python3.7/site-packages/encyc_core-_-py3.7.egg/encyc/models/wikipage.py", line 297, in <listcomp>
TypeError: string indices must be integers
```
