### ISSUE TITLE
Articles are not being publishing/updated

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-core#22]
An article with an em-dash character in the title will not publish in the production encyclopedia. Removing the em-dash did not seem to remediate the issue. See: 

https://editors.densho.org/wiki/The_Japanese_American_Cases--A_Disaster/Our_Worst_Wartime_Mistake_(article)

Update (gjost): The problem is that encyc-core article publishing is hitting an error on the first article.  See comments below.

**Comment by gjost** [comment]
The em-dash or lack thereof does not seem to be the issue.  I was able to publish [the article](http://encyclopedia.densho.org/The%20Japanese%20American%20Cases--A%20Disaster/Our%20Worst%20Wartime%20Mistake%20(article)/).

The problem was with an earlier article that crashed the publishing process before it reached the article in question:
```
(encyccore) encyc@fuzzy:/opt/encyc-core$ encyc articles
Debug mode is off
2019-12-03 13:53:40.689004 hosts: [{'host': '192.168.0.20', 'port': '9200'}]
2019-12-03 13:53:40.689426 index: encyc-20180226c
2019-12-03 13:53:40.689511 ------------------------------------------------------------------------
2019-12-03 13:53:40.689539 getting mw_authors,articles...
2019-12-03 13:53:40.754789 getting es_articles...
2019-12-03 13:53:42.958905 mediawiki articles: 1604
2019-12-03 13:53:42.958994 elasticsearch articles: 1482
2019-12-03 13:53:42.959013 determining new,delete...
2019-12-03 13:53:43.164398 articles to update: 34
2019-12-03 13:53:43.164494 getting encycrg titles...
2019-12-03 13:53:51.191701 encycrg titles: 656
2019-12-03 13:53:51.191773 adding articles...
2019-12-03 13:53:51.191786 --------------------
2019-12-03 13:53:51.191797 1/34 The War Outside (book)
2019-12-03 13:53:51.191808 getting from mediawiki
Traceback (most recent call last):
  File "/opt/encyc-core/venv/encyccore/bin/encyc", line 14, in <module>
    load_entry_point('encyc-core===-', 'console_scripts', 'encyc')()
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/encyc/cli.py", line 180, in articles
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 32, in with_profiling
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 359, in articles
  File "build/bdist.linux-x86_64/egg/encyc/models/legacy.py", line 277, in page
  File "build/bdist.linux-x86_64/egg/encyc/models/legacy.py", line 365, in _mkpage
  File "build/bdist.linux-x86_64/egg/encyc/models/wikipage.py", line 50, in parse_mediawiki_text
  File "build/bdist.linux-x86_64/egg/encyc/models/wikipage.py", line 298, in _remove_primary_sources
TypeError: string indices must be integers
```

**Comment by gjost** [comment]
Problem was an outdated setting for the PSMS SOURCES_API base URL.
Fixed in [ansible-colo](https://github.com/densho/ansible-colo) commit [6ed37a0](https://github.com/densho/ansible-colo/commit/6ed37a0d8fdd216c1a35d03b20418ba7ac23f386) and configuration updated.
