### ISSUE TITLE
"encyc articles" command fails with "JSONDecodeError" exception (version tag 4.0.4)

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-core#30]
`encyc articles` command fails with `JSONDecodeError` exception. This is on production publish server running 4.0.4 at commit 227c6cd0fe1bea2fac451a1240f2b92a2ad69aa9.

```
(encyccore) encyc@fuzzy:/opt/encyc-core$ encyc articles --force --hosts 192.168.0.20:9200
2020-07-14 21:15:35.654617 ------------------------------------------------------------------------
2020-07-14 21:15:35.654799 getting mw_authors,articles...
2020-07-14 21:15:35.705390 getting es_articles...
2020-07-14 21:15:36.859379 mediawiki articles: 1609
2020-07-14 21:15:36.859505 elasticsearch articles: 1493
2020-07-14 21:15:36.859543 forcibly update all articles
2020-07-14 21:15:36.867782 articles to update: 1493
2020-07-14 21:15:36.867860 getting encycrg titles...
Traceback (most recent call last):
  File "/opt/encyc-core/venv/encyccore/bin/encyc", line 36, in <module>
    sys.exit(load_entry_point('encyc-core===-', 'console_scripts', 'encyc')())
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/encyc_core-_-py3.5.egg/encyc/cli.py", line 164, in articles
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/encyc_core-_-py3.5.egg/encyc/publish.py", line 28, in with_profiling
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/encyc_core-_-py3.5.egg/encyc/publish.py", line 234, in articles
  File "/opt/encyc-core/venv/encyccore/lib/python3.5/site-packages/encyc_core-_-py3.5.egg/encyc/models/elastic.py", line 325, in rg_titles
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

NOTE: This command worked previously. Does __not__ fail at commit 477eb855245c06e7fc298f7047dadd51f9dbe2ce (running on chogen at HQ)

**Comment by gjost** [comment]
The problem was an outdated API URL for encyc-rg.  The problem was corrected in `ansible-colo` commit `3a47712` and applied in the production environment.
