### ISSUE TITLE
Problem running sources

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-core#7]
Error when running `encyc sources` on dev machine:
```
(encyccore)encyc@denshodeb8:/opt/encyc-core$ encyc sources
2017-12-12 22:39:50.564408 --------------------
2017-12-12 22:39:50.564452 981/1192 en-denshopd-i67-00075-1
2017-12-12 22:39:50.564501 getting from PSMS: "en-denshopd-i67-00075-1"
2017-12-12 22:39:50.871447 en-denshopd-i67-00075-1
2017-12-12 22:39:50.871646 getting from Elasticsearch
WARNING:elasticsearch:GET http://192.168.56.1:9200/encyc-20171213a/sources/en-denshopd-i67-00075-1 [status:404 request:0.002s]
2017-12-12 22:39:50.875020 not in ES
Traceback (most recent call last):
  File "/opt/encyc-core/venv/encyccore/bin/encyc", line 11, in <module>
    load_entry_point('encyc-core===-', 'console_scripts', 'encyc')()
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/encyc/cli.py", line 199, in sources
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 32, in with_profiling
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 468, in sources
  File "build/bdist.linux-x86_64/egg/encyc/models/elastic.py", line 610, in from_psms
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by gjost** [comment]
Fixed while fixing something else.
