### ISSUE TITLE
AttributeError when running encyc sources --force

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-core#8]
```
$ encyc sources --force
...
2018-01-16 12:14:49.954814 --------------------
2018-01-16 12:14:49.954948 242/1195 en-denshopd-i67-00075-1
2018-01-16 12:14:49.955043 getting from PSMS: "en-denshopd-i67-00075-1"
2018-01-16 12:14:49.976363 en-denshopd-i67-00075-1
2018-01-16 12:14:49.976491 getting from Elasticsearch
2018-01-16 12:14:49.980545 en-denshopd-i67-00075-1
Traceback (most recent call last):
  File "/opt/encyc-core/venv/encyccore/bin/encyc", line 14, in <module>
    load_entry_point('encyc-core===-', 'console_scripts', 'encyc')()
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/encyc-core/venv/encyccore/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/encyc/cli.py", line 199, in sources
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 32, in with_profiling
  File "build/bdist.linux-x86_64/egg/encyc/publish.py", line 468, in sources
  File "build/bdist.linux-x86_64/egg/encyc/models/elastic.py", line 610, in from_psms
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by gjost** [comment]
Fixed in 7830211.
